name: CD
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy-to-test:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew tap databricks/tap
          brew install databricks

      - name: Check Databricks CLI version
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          databricks --version

      - name: Install Poetry
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install poetry

      - name: Check Poetry version
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          poetry --version

      - name: Run bundle deploy
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          databricks bundle deploy --target $TARGET
        env:
          TARGET: ${{ vars.TARGET }}
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ vars.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

  deploy-to-production:
    runs-on: ubuntu-latest
    environment: production
    needs: deploy-to-prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew tap databricks/tap
          brew install databricks

      - name: Check Databricks CLI version
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          databricks --version

      - name: Install Poetry
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install poetry

      - name: Check Poetry version
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          poetry --version

      - name: Run bundle deploy
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          databricks bundle deploy --target $TARGET
        env:
          TARGET: ${{ vars.TARGET }}
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ vars.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
